"""Path-based rate limiting for auth endpoints.

Deliberately dependency-free and in-process. That means limits are per
instance and reset on deploy — enough to stop credential stuffing and reset-
email abuse from one IP, not enough to coordinate across replicas. If you
scale past one instance and care, move the buckets to Redis; the interface
here won't change.

It is a middleware rather than a decorator because the routes being protected
are generated by fastapi-users, so there is nothing of ours to decorate.

Memory is bounded: buckets are kept in least-recently-used order and the
oldest are evicted past MAX_BUCKETS, so a flood of distinct clients cannot
grow the table without limit (Production Standard AUTH-3).
"""

import time
from collections import OrderedDict, deque
from collections.abc import Awaitable, Callable

from fastapi import Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.config import Settings

MAX_BUCKETS = 10_000


def parse_rule(rule: str) -> tuple[int, int]:
    """'10/minute' -> (10, 60). Accepts second|minute|hour|day."""
    amount, _, period = rule.partition("/")
    seconds = {
        "second": 1,
        "minute": 60,
        "hour": 3600,
        "day": 86400,
    }
    key = period.strip().rstrip("s").lower()
    if key not in seconds:
        raise ValueError(f"Unknown rate limit period: {rule!r}")
    return int(amount), seconds[key]


def client_ip(request: Request) -> str:
    """The connecting client's IP, as reported by Railway's edge.

    Railway overwrites X-Real-IP on every request, so a client cannot forge
    it. X-Forwarded-For is deliberately ignored: which entry is trustworthy
    depends on every proxy in the chain, and getting that wrong turns the
    rate limit into a suggestion. Without the header (local dev, tests) fall
    back to the socket peer.
    """
    real_ip = request.headers.get("X-Real-IP")
    if real_ip and real_ip.strip():
        return real_ip.strip()
    return request.client.host if request.client else "unknown"


class RateLimitMiddleware(BaseHTTPMiddleware):
    def __init__(
        self, app, settings: Settings, max_buckets: int = MAX_BUCKETS
    ) -> None:
        super().__init__(app)
        account_change = parse_rule(settings.RATE_LIMIT_ACCOUNT_CHANGE)
        # (method, exact path) -> rule
        self._rules: dict[tuple[str, str], tuple[int, int]] = {
            ("POST", "/api/auth/login"): parse_rule(settings.RATE_LIMIT_LOGIN),
            ("POST", "/api/auth/register"): parse_rule(
                settings.RATE_LIMIT_REGISTER
            ),
            ("POST", "/api/auth/forgot-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
            ("POST", "/api/auth/reset-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
            # Both take a password, so both are guessing oracles.
            ("PATCH", "/api/users/me"): account_change,
            ("DELETE", "/api/users/me"): account_change,
        }
        self._max_buckets = max_buckets
        self._hits: OrderedDict[str, deque[float]] = OrderedDict()

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        rule = self._rules.get((request.method, request.url.path))
        if rule is None:
            return await call_next(request)

        limit, window = rule
        bucket_key = f"{request.method} {request.url.path} {client_ip(request)}"
        now = time.monotonic()

        hits = self._hits.get(bucket_key)
        if hits is None:
            hits = deque()
            self._hits[bucket_key] = hits
            while len(self._hits) > self._max_buckets:
                self._hits.popitem(last=False)
        else:
            self._hits.move_to_end(bucket_key)
        while hits and now - hits[0] > window:
            hits.popleft()

        if len(hits) >= limit:
            retry_after = int(window - (now - hits[0])) + 1
            return JSONResponse(
                status_code=429,
                content={"detail": "Too many requests. Try again shortly."},
                headers={"Retry-After": str(retry_after)},
            )

        hits.append(now)
        return await call_next(request)
